### ISSUE TITLE
Add dependencies in setup.py

### ISSUE THREAD

**Issue by duetosymmetry** [nilsleiffischer/spec-diagnose#1]
This is the field `install_requires=['numpy',...]`. The current deps seem to be:
- numpy
- h5py
- tqdm
- matplotlib
and standard stuff that comes with python.

**Comment by haraldp271** [comment]
Hi Nils, 
since you know python, do you have the five minutes to do this?  Thanks!

**Comment by nilsvu** [comment]
Sure, done 👍
